---
title: "Untitled"
author: "Jia Nie"
date: "11/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Get FASTQ and Reference Data
```{bash}
mkdir /home/jianie/yard/run_cellranger_count
cd /home/jianie/yard/run_cellranger_count
```


# References - 2020-A (July 7, 2020)
```{bash}
cd /home/jianie/yard/refdata/refdata-cellranger-GRCh38-3.0.0
cd /home/jianie/yard/refdata/refdata-gex-mm10-2020-A
cd /home/jianie/yard/refdata/refdata-gex-GRCh38-and-mm10-2020-A
cd /home/jianie/yard/refdata/Cjacchus_012021
```


## set up the variables
```{bash}
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --help
```

# 20210126
# 76615-V5
# Run cellranger count
```{bash}
cellranger count --id=76615-V5 \
--fastqs=/media/jianie/Seagate_SequencingFiles_1/20210126_UTA_NovaSeq_L3_fastq/NieFASTQ_P0111212/NieFASTQ_P0111212Dual/outs/fastq_path/HTK5NDSXY/ \
--sample=76615-V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r2-length 91
2021-10-12 14:09:52 [runtime] (ready) 
2021-10-12 17:43:36 Shutting down.
```
# 20210716_L2
# 76632-V5
# Run cellranger count
```{bash}
cellranger count --id=76632-V5 \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210716_L2_fastq_single_cellranger/outs/fastq_path/HGK5TDSX2/76632-V5 \
--sample=76632-V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r2-length 91
```
# Total time 3 hr
2021-09-23 10:16:13 [runtime] (ready)  
2021-09-23 13:23:23 Shutting down.

# 20210830_L3
# 76632-V11
# Run cellranger count
```{bash}
cellranger count --id=76632-V11 \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210830_L3_fastq_dual/766-32 \
--sample=766-32 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r2-length 91
```
# Total time: 2 hr
# 2021-09-29 17:23:08 [runtime] (ready) 
# 2021-09-29 19:17:00 Shutting down.

# 20210830_L3
# 76643-V5
# Run cellranger count
```{bash}
cellranger count --id=76643-V5 \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210830_L3_fastq_dual/766-43 \
--sample=766-43 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r2-length 91
```
# Total time: 2 hr
# 2021-09-29 19:17:02 [runtime] (ready) 
# 2021-09-29 21:17:36 Shutting down.


# 20210830_L3
# 76647-V5
# Run cellranger count
```{bash}
cellranger count --id=76647-V5 \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210830_L3_fastq_dual/766-47_V5 \
--sample=766-47-V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r2-length 91
```
# Total time: 2 hr
# 2021-09-29 21:17:37 [runtime] (ready) 
# 2021-09-29 23:50:52 Shutting down.


# 20210830_L3
# 76638-V5
# Run cellranger count
```{bash}
cellranger count --id=76638-V5 \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210830_L3_fastq_dual/766-38_Fat \
--sample=766-38-Fat \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r2-length 91
```
# Total time: 2 hr
# 2021-09-29 23:50:54 [runtime] (ready)  
# 2021-09-30 01:33:37 Shutting down.


# 20210830_L3
# 76638-V5_Muscle
# Run cellranger count
```{bash}
cellranger count --id=76638-V5_Muscle \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210830_L3_fastq_dual/766-38_Muscle \
--sample=766-38-Muscle \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r2-length 91
```
# Total time: 2 hr
# 2021-09-30 01:33:38 [runtime] (ready) 
# 2021-09-30 03:05:36 Shutting down.

# 20210830_L3
# 76638-V5_Muscle
# Run cellranger count
```{bash}
cellranger count --id=76638-V5_Muscle_force \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210830_L3_fastq_dual/766-38_Muscle \
--sample=766-38-Muscle \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--force-cells=10000 \
--r2-length 91
```
2021-10-15 07:58:43 [runtime] (ready) 
2021-10-15 09:32:01 Shutting down.


# 20210830_L3
# 76649-V5
# Run cellranger count
```{bash}
cellranger count --id=76649-V5 \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210830_L3_fastq_dual/766-49_V5 \
--sample=766-49-V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r2-length 91
```
# Total time: 2 hr
# 2021-09-30 07:31:41 [runtime] (ready)  
# 2021-09-30 09:52:45 Shutting down.


--------
# 20211105_L3_L4_single
```{bash}
## 76632_V5
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76632_V5 \
--fastqs=/media/jianie/DATA/20211105_L3_L4_fastq_single/76632_V5 \
--sample=76632_V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime
# Total time: 48 min
# 2021-11-16 17:00:01 [runtime] (ready)
# 2021-11-16 17:48:54 Shutting down.

## STARR_049
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=STARR_049 \
--fastqs=/media/jianie/DATA/20211105_L3_L4_fastq_single/STARR_049 \
--sample=STARR_049 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime
# Total time:  1 hr
# 2021-11-16 17:48:55 [runtime] (ready) 
# 2021-11-16 18:53:26 Shutting down.

## 76656_V5
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76656_V5 \
--fastqs=/media/jianie/DATA/20211105_L3_L4_fastq_single/76656_V5 \
--sample=76656_V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime
# Total time: 3 hr
# 2021-11-17 07:27:10 [runtime] (ready) 
# 2021-11-17 10:27:35 Shutting down.
```

# 20211105_L3_L4_dual
```{bash}
## 76632_V11
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76632_V11 \
--fastqs=/media/jianie/DATA/20211105_L3_L4_fastq_dual/76632_V11 \
--sample=76632_V11 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime
# Total time: 
# Done

## 76643_V5
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76643_V5 \
--fastqs=/media/jianie/DATA/20211105_L3_L4_fastq_dual/76643_V5 \
--sample=76643_V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime
# Total time: Done
# 2021-11-17 12:04:59 Shutting down.

## 76647_V5
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76647_V5 \
--fastqs=/media/jianie/DATA/20211105_L3_L4_fastq_dual/76647_V5 \
--sample=76647_V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime
# Total time: 3hr
# 2021-11-17 12:05:01 [runtime] (ready)  
# 2021-11-17 15:25:03 Shutting down.

## STARR_051
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=STARR_051 \
--fastqs=/media/jianie/DATA/20211105_L3_L4_fastq_dual/STARR_051 \
--sample=STARR_051 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime
# Total time: 2 hr
# 2021-11-17 15:25:04 [runtime] (ready)  
# 2021-11-17 17:06:09 Shutting down.

## 76649_V5
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76649_V5 \
--fastqs=/media/jianie/DATA/20211105_L3_L4_fastq_dual/76649_V5 \
--sample=76649_V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime
# Total time: 4 hr
# 2021-11-17 17:06:10 [runtime] (ready)  
# 2021-11-17 21:21:22 Shutting down.

## 76638_V5_Muscle
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76638_V5_Muscle \
--fastqs=/media/jianie/DATA/20211105_L3_L4_fastq_dual/76638_V5_Muscle \
--sample=76638_V5_Muscle \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime
# Total time: 2 hr
# 2021-11-17 21:21:24 [runtime] (ready)  
# 2021-11-17 23:23:05 Shutting down.

## 76638_V5
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76638_V5 \
--fastqs=/media/jianie/DATA/20211105_L3_L4_fastq_dual/76638_V5 \
--sample=76638_V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime
# Total time: 2hr
# 2021-11-17 23:23:07 [runtime] (ready)  
# 2021-11-18 01:07:54 Shutting down.

## 76658_V5
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76658_V5 \
--fastqs=/media/jianie/DATA/20211105_L3_L4_fastq_dual/76658_V5 \
--sample=76658_V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime
# Total time: 3 hr
# 2021-11-18 01:07:56 [runtime] (ready)   
# 2021-11-18 03:56:50 Shutting down.

## 76658_V5_force10000
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76658_V5_force10000 \
--fastqs=/media/jianie/SequencingFiles_3/20211105_L3_L4_fastq_dual/76658_V5 \
--sample=76658_V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--force-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime
# Total time:  hr
# 2021-12-06 16:00:25 [runtime] (ready) 


## 76638_V11
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76638_V11 \
--fastqs=/media/jianie/DATA/20211105_L3_L4_fastq_dual/76638_V11 \
--sample=76638_V11 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime
# Total time: 2.5 hr
# 2021-11-18 03:56:52 [runtime] (ready) 
# 2021-11-18 06:21:51 Shutting down.

## 76638_V11_force10000
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76638_V11_force10000 \
--fastqs=/media/jianie/SequencingFiles_3/20211105_L3_L4_fastq_dual/ \
--sample=76638_V11 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--force-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime \
--project 76638_V11
# Total time:  hr
# 
```



# combine
```{bash}
# STARR_051_combine
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=STARR_051_combine \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210830_L3_fastq_dual/,/media/jianie/DATA/20211105_L3_L4_fastq_dual/ \
--sample=STARR_051 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime \
--project STARR_051
# Total time: 3 hr
# 2021-11-18 13:17:57 [runtime] (ready) 
# 2021-11-18 16:10:37 Shutting down.

# STARR_049_combine: mistake for dual
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=STARR_049_combine \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210716_L2_fastq_single_cellranger/outs/fastq_path/HGK5TDSX2/,/media/jianie/DATA/20211105_L3_L4_fastq_dual/ \
--sample=STARR_049 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime \
--project STARR_049
# Total time: 3 hr
# 2021-11-19 10:57:51 [runtime] (ready) 
# 2021-11-19 13:39:51 Shutting down.

# STARR_049_combine: mistake for dual
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=STARR_049_combine \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210716_L2_fastq_single_cellranger/outs/fastq_path/HGK5TDSX2/,/media/jianie/SequencingFiles_3/20211105_L3_L4_fastq_single/ \
--sample=STARR_049 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime \
--project STARR_049
# Total time: 

```


```{bash}
# 76632_V11_combine
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76632_V11_combine \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210830_L3_fastq_dual/,/media/jianie/DATA/20211105_L3_L4_fastq_dual/ \
--sample=76632_V11 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime \
--project 76632_V11
# Total time: 1.5 hr
# 2021-11-18 16:10:40 [runtime] (ready)  
# 2021-11-18 18:45:55 Shutting down.

# 76632_V5_combine: mistake in dual
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76632_V5_combine \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210716_L2_fastq_single_cellranger/outs/fastq_path/HGK5TDSX2/,/media/jianie/DATA/20211105_L3_L4_fastq_dual/ \
--sample=76632_V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime \
--project 76632_V5
# Total time: 3hr
# 2021-11-19 16:22:24 [runtime] (ready) 
# 2021-11-19 19:21:07 Shutting down.

# 76632_V5_combine: corrected
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76632_V5_combine \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210716_L2_fastq_single_cellranger/outs/fastq_path/HGK5TDSX2/,/media/jianie/SequencingFiles_3/20211105_L3_L4_fastq_single/ \
--sample=76632_V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime \
--project 76632_V5
# Total time: 3.5 hr
# 2021-12-06 12:23:34 [runtime] (ready) 
# 2021-12-06 16:00:23 Shutting down.


# 76638_V5_combine
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76638_V5_combine \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210830_L3_fastq_dual/,/media/jianie/DATA/20211105_L3_L4_fastq_dual/ \
--sample=76638_V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime \
--project 76638_V5
# Total time: 3 hr
# 2021-11-18 18:45:58 [runtime] (ready)  
# 2021-11-18 21:40:40 Shutting down.

# 76638_V5_Muscle_combine
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76638_V5_Muscle_combine \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210830_L3_fastq_dual/,/media/jianie/DATA/20211105_L3_L4_fastq_dual/ \
--sample=76638_V5_Muscle \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime \
--project 76638_V5_Muscle
# Total time: 3 hr
# 2021-11-19 19:21:09 [runtime] (ready)  
# 2021-11-19 22:23:00 Shutting down.

# 76643_V5_combine
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76643_V5_combine \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210830_L3_fastq_dual/,/media/jianie/DATA/20211105_L3_L4_fastq_dual/ \
--sample=76643_V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime \
--project 76643_V5
# Total time: 2 hr
# 2021-11-18 21:40:42 [runtime] (ready) 
# 2021-11-18 23:37:30 Shutting down.

# 76647_V5_combine
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76647_V5_combine \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210830_L3_fastq_dual/,/media/jianie/DATA/20211105_L3_L4_fastq_dual/ \
--sample=76647_V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime \
--project 76647_V5
# Total time: 5 hr
# 2021-11-18 23:37:31 [runtime] (ready) 
# 2021-11-19 04:58:49 Shutting down.

# 76649_V5_combine
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76649_V5_combine \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210830_L3_fastq_dual/,/media/jianie/DATA/20211105_L3_L4_fastq_dual/ \
--sample=76649_V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--expect-cells=10000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime \
--project 76649_V5
# Total time: 
# 2021-11-19 04:58:51 [runtime] (ready) 
# 2021-11-19 10:57:51 Shutting down.

# 76649_V5_combine_force15000
cd /home/jianie/yard/run_cellranger_count
export PATH=/home/jianie/yard/apps/cellranger-6.1.1:$PATH
cellranger count --id=76649_V5_combine_force15000 \
--fastqs=/media/jianie/Seagate_SequencingFiles_2/20210830_L3_fastq_dual/,/media/jianie/SequencingFiles_3/20211105_L3_L4_fastq_dual/ \
--sample=76649_V5 \
--transcriptome=/media/jianie/DATA/refdata/refdata-cellranger-GRCh38-3.0.0 \
--include-introns=TRUE \
--force-cells=15000 \
--r1-length 26 \
--r2-length 90 \
--chemistry threeprime \
--project 76649_V5

