---
title: "Combine counts results"
author: "Jia Nie"
date: "11/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

install packages
```{r package, include=FALSE}
packageList <- c("rio", "dplyr")
for (package in packageList) {
  if(!require(package, character.only = TRUE)){
    install.packages(package); require(package, character.only = TRUE); }
}
```

# Combine Metrics Summary to Counts Records
```{r}
aggr <- rio::import("/media/jianie/DATA/UTHSC_cellranger_codes_files/ExperimentSummaryFiles/Form 3_cellranger_counts_summary.xlsx")
aggr2 <- aggr[-which(aggr$Status %in% c("Delete", "middle")), ]
df.all <- data.frame()
for (pp in aggr2$Metrics) {
  dx <- rio::import(paste0(pp))
  dx[] <- lapply(dx, function(x){ if(is.integer(x)) as.numeric(x) else x} )
  dx[] <- lapply(dx, function(x){ if(is.double(x)) as.numeric(as.integer(x)) else x} )
  dx[] <- lapply(dx, function(x){ if(is.factor(x)) as.numeric(as.character(x)) else x} )
  dx[] <- lapply(dx[], function(x){ if(is.character(x)) as.numeric(gsub("%|,", "", x)) else x} )
  # sapply(dx, class)
  # sapply(dx, mode)
  library(tibble)
  dx <- add_column(dx, sample_id_ori = aggr2[which(aggr2$Metrics == pp), "sample_id_ori"], .before = 1)
  dx <- add_column(dx, Counts_List = aggr2[which(aggr2$Metrics == pp), "Counts_List"], .before = 1)
  if ( match(pp, aggr2$Metrics) == 1 ) {df.all <- rbind(df.all, dx) } else {
    if ( length(setdiff(colnames(df.all), colnames(dx))) > 0 ) {df.all <- dplyr::bind_rows(df.all, dx)} else {
      df.all <- rbind(df.all, dx)} } 
  # print(pp)
}

df.all2 <- merge(df.all, aggr2, by = c("Counts_List", "sample_id_ori"))
df.all2 <- df.all2[order(df.all2$Counts_List),]
saveRDS(df.all2, file = "/media/jianie/DATA/UTHSC_cellranger_codes_files/ExperimentSummaryFiles/Counts_Sequencing_Combine.Rds")
write.csv(df.all2, file = "/media/jianie/DATA/UTHSC_cellranger_codes_files/ExperimentSummaryFiles/Counts_Sequencing_Combine.csv", row.names = FALSE)
```

# Select rows from project for Aggregation in Cellranger
```{r}
cols = c("sample_id", "molecule_h5", "sample_id_ori", "List")
```
STARR project
```{r}
STARR <- df.all2[which(df.all2$Project == "STARR" & df.all2$Agg == "Yes"), ]
write.csv(STARR[cols], file = "/media/jianie/DATA/UTHSC_cellranger_codes_files/AggrFiles/STARR.agg.csv")
```
SGLT2 project
```{r}
SGLT2 <- df.all2[which(df.all2$Project == "SGLT2" & df.all2$Agg == "Yes"), ]
write.csv(SGLT2[cols], file = "/media/jianie/DATA/UTHSC_cellranger_codes_files/AggrFiles/SGLT2.agg.csv")
```
STARR & SGLT2-V5 project
```{r}
STARR2 <- df.all2[which((df.all2$Project == "STARR" | df.all2$sample_id %in% c("76615-V5", "76632-V5", "76638-V5", "76643-V5",
                                                                              "76647-V5", "76649-V5", "76656-V5", "76658-V5")) & 
                         df.all2$Agg == "Yes") , ]
write.csv(STARR2[cols], file = "/media/jianie/DATA/UTHSC_cellranger_codes_files/AggrFiles/STARR2.agg.csv")
```
